### ISSUE TITLE
Static image size

### ISSUE THREAD

**Issue by wrdana** [snag87/hunt-assignment#2]
width="auto" height="140"

![image](https://cloud.githubusercontent.com/assets/6061907/16298510/687442c2-393e-11e6-9312-fd9e0f711ecc.png)

Causes overflowing in smaller devices

**Comment by HaymanLiron** [comment]
solved using a media query
![image](https://cloud.githubusercontent.com/assets/19637145/16411487/ef13b93a-3d2f-11e6-8448-9e5745cfbe0e.png)
